export const FOODS = [
  { id: 1,  name: 'Burger',         emoji: '🍔', tags: ['fast food', 'meat', 'american'],         moods: ['comfort food', 'quick meal', 'cheap'],          description: 'Juicy, stacked, and unapologetically satisfying. The kind of meal that fixes a bad day in three bites.' },
  { id: 2,  name: 'Sushi',          emoji: '🍣', tags: ['japanese', 'seafood', 'asian'],           moods: ['treat yourself', 'healthy-ish'],                 description: 'Clean, precise, and a little fancy. You\'re not just eating — you\'re having a moment.' },
  { id: 3,  name: 'Pizza',          emoji: '🍕', tags: ['italian', 'fast food'],                   moods: ['comfort food', 'cheap', 'quick meal'],           description: 'The universal answer to "I don\'t know what I want." Crispy edges, melted cheese, no regrets.' },
  { id: 4,  name: 'Kebab',          emoji: '🥙', tags: ['middle eastern', 'street food', 'meat'],  moods: ['cheap', 'quick meal'],                           description: 'Fast, filling, and somehow always the right call. Street food at its most honest.' },
  { id: 5,  name: 'Pasta',          emoji: '🍝', tags: ['italian'],                                moods: ['comfort food', 'cheap'],                         description: 'Warm, simple, and deeply comforting. The culinary equivalent of a hug after a long day.' },
  { id: 6,  name: 'Ramen',          emoji: '🍜', tags: ['japanese', 'asian'],                      moods: ['comfort food', 'quick meal'],                    description: 'Rich broth, soft noodles, perfectly soft egg. One bowl and everything feels manageable again.' },
  { id: 7,  name: 'Tacos',          emoji: '🌮', tags: ['mexican', 'street food', 'spicy'],        moods: ['cheap', 'quick meal', 'comfort food'],           description: 'Small but mighty. Two or three of these and you\'re in a completely different mood.' },
  { id: 8,  name: 'Fried Chicken',  emoji: '🍗', tags: ['fast food', 'meat', 'american'],          moods: ['comfort food', 'cheap', 'quick meal'],           description: 'Crunchy outside, tender inside, impossible to eat just one piece. Pure comfort in every bite.' },
  { id: 9,  name: 'Dumplings',      emoji: '🥟', tags: ['chinese', 'asian'],                       moods: ['comfort food', 'cheap'],                         description: 'Little pockets of joy. Steamed or fried, they hit different when you need something real.' },
  { id: 10, name: 'Steak',          emoji: '🥩', tags: ['american', 'grill', 'meat'],              moods: ['treat yourself'],                                description: 'Not a meal — an event. You\'ve earned this. Order it medium-rare and don\'t overthink it.' },
  { id: 11, name: 'Burrito',        emoji: '🌯', tags: ['mexican'],                                moods: ['cheap', 'quick meal', 'comfort food'],           description: 'Everything you need, wrapped up tight. Filling, fast, and deeply underrated as comfort food.' },
  { id: 12, name: 'BBQ Ribs',       emoji: '🍖', tags: ['american', 'grill', 'meat'],              moods: ['treat yourself', 'comfort food'],                description: 'Slow-cooked, falling off the bone, smoky and sticky. This is a meal you remember.' },
  { id: 13, name: 'Hot Dog',        emoji: '🌭', tags: ['fast food', 'american', 'meat'],          moods: ['cheap', 'quick meal'],                           description: 'Underestimated every time, regretted never. Sometimes the simplest thing is exactly right.' },
  { id: 14, name: 'Sandwich',       emoji: '🥪', tags: ['american', 'quick'],                      moods: ['cheap', 'quick meal', 'healthy-ish'],            description: 'Honest, quick, and endlessly customizable. The workhorse of good decisions under time pressure.' },
  { id: 15, name: 'Salad',          emoji: '🥗', tags: ['healthy', 'vegetarian'],                  moods: ['healthy-ish'],                                   description: 'Light, fresh, and actually satisfying when done right. Your future self will appreciate this.' },
  { id: 16, name: 'Poke Bowl',      emoji: '🫙', tags: ['hawaiian', 'seafood', 'healthy'],         moods: ['healthy-ish', 'treat yourself'],                 description: 'Fresh fish, sticky rice, creamy sauce. Healthy enough to feel good about, tasty enough to actually want.' },
  { id: 17, name: 'Wings',          emoji: '🍗', tags: ['fast food', 'meat', 'spicy'],             moods: ['comfort food', 'cheap'],                         description: 'Messy, saucy, and absolutely worth it. The kind of food that requires full commitment.' },
  { id: 18, name: 'Crepes',         emoji: '🥞', tags: ['french', 'sweet'],                        moods: ['treat yourself', 'cheap'],                       description: 'Thin, delicate, and a little bit indulgent. Sweet or savoury — either way you\'re winning.' },
  { id: 19, name: 'Indian Curry',   emoji: '🍛', tags: ['indian', 'spicy'],                        moods: ['comfort food', 'treat yourself'],                description: 'Complex, warming, and full of depth. This is what you eat when you want to actually taste something.' },
  { id: 20, name: 'Pho',            emoji: '🍲', tags: ['vietnamese', 'asian'],                    moods: ['comfort food', 'healthy-ish'],                   description: 'A bowl of deeply flavoured broth that fixes almost anything. Light but satisfying in all the right ways.' },
  { id: 21, name: 'Pancakes',       emoji: '🥞', tags: ['american', 'sweet', 'breakfast'],         moods: ['comfort food', 'treat yourself'],                description: 'Fluffy, golden, and a little bit of a treat no matter what time it is. Some meals are just moods.' },
  { id: 22, name: 'Nachos',         emoji: '🫔', tags: ['mexican', 'fast food', 'spicy'],          moods: ['cheap', 'comfort food'],                         description: 'Chaotic, crunchy, smothered in cheese and toppings. Exactly what you need when you want something fun.' },
  { id: 23, name: 'Gyros',          emoji: '🥙', tags: ['greek', 'street food', 'meat'],           moods: ['cheap', 'quick meal'],                           description: 'Herby meat, crispy edges, cool tzatziki. Street food that punches way above its price point.' },
  { id: 24, name: 'Pad Thai',       emoji: '🍜', tags: ['thai', 'asian'],                          moods: ['cheap', 'comfort food'],                         description: 'Tangy, nutty, a little sweet. One of those dishes that always tastes better than you remembered.' },
  { id: 25, name: 'Fish & Chips',   emoji: '🐟', tags: ['british', 'seafood', 'fried'],            moods: ['comfort food', 'cheap'],                         description: 'Crispy batter, flaky fish, a mountain of chips. Straightforward and completely satisfying.' },
  { id: 26, name: 'Shawarma',       emoji: '🌯', tags: ['middle eastern', 'street food', 'meat'],  moods: ['cheap', 'quick meal'],                           description: 'Thinly sliced, perfectly spiced, wrapped tight. One of the best fast meals ever invented.' },
  { id: 27, name: 'Falafel',        emoji: '🧆', tags: ['middle eastern', 'vegetarian'],           moods: ['cheap', 'healthy-ish'],                          description: 'Crispy chickpea balls that make you forget you\'re eating plant-based. Light, cheap, and genuinely good.' },
  { id: 28, name: 'Noodles',        emoji: '🍜', tags: ['asian', 'chinese'],                       moods: ['cheap', 'quick meal', 'comfort food'],           description: 'Endlessly satisfying and ready fast. Sometimes the simplest bowl of noodles is the answer.' },
  { id: 29, name: 'Waffles',        emoji: '🧇', tags: ['american', 'sweet', 'breakfast'],         moods: ['treat yourself', 'comfort food'],                description: 'Golden, crisp-edged, and slightly indulgent. A meal that doubles as a treat and nobody can argue with that.' },
  { id: 30, name: 'Quesadilla',     emoji: '🫓', tags: ['mexican', 'quick'],                       moods: ['cheap', 'quick meal', 'comfort food'],           description: 'Cheese pulling between two crispy tortillas. Fast, satisfying, and one of life\'s more reliable pleasures.' },
  { id: 31, name: 'Dim Sum',        emoji: '🥟', tags: ['chinese', 'asian'],                       moods: ['treat yourself', 'comfort food'],                description: 'Delicate little parcels, steamed to perfection. The kind of meal that feels both special and deeply familiar.' },
  { id: 32, name: 'Grilled Salmon', emoji: '🐟', tags: ['seafood', 'healthy', 'grill'],            moods: ['healthy-ish', 'treat yourself'],                 description: 'Flaky, rich, and genuinely good for you. The rare meal where doing the right thing still feels like a treat.' },
]

export const MOODS = [
  { id: 'all',           label: 'All',           emoji: '✦' },
  { id: 'cheap',         label: 'Cheap Eats',    emoji: '💸' },
  { id: 'comfort food',  label: 'Comfort Food',  emoji: '🫂' },
  { id: 'healthy-ish',   label: 'Healthy-ish',   emoji: '🌿' },
  { id: 'treat yourself',label: 'Treat Yourself',emoji: '🍾' },
  { id: 'quick meal',    label: 'Quick Meal',    emoji: '⚡' },
]

export const EXCLUDES = [
  { tag: 'spicy',        label: 'Spicy 🌶️' },
  { tag: 'seafood',      label: 'Seafood 🦑' },
  { tag: 'fast food',    label: 'Fast Food 🍟' },
  { tag: 'meat',         label: 'Meat 🥩' },
  { tag: 'sweet',        label: 'Sweet 🍬' },
  { tag: 'japanese',     label: 'Japanese' },
  { tag: 'mexican',      label: 'Mexican' },
]
