export const FOODS = [
  { id: 1,  name: 'Burger',         emoji: '🍔', tags: ['fast food', 'meat', 'american'],         moods: ['comfort food', 'quick meal', 'cheap'] },
  { id: 2,  name: 'Sushi',          emoji: '🍣', tags: ['japanese', 'seafood', 'asian'],           moods: ['treat yourself', 'healthy-ish'] },
  { id: 3,  name: 'Pizza',          emoji: '🍕', tags: ['italian', 'fast food'],                   moods: ['comfort food', 'cheap', 'quick meal'] },
  { id: 4,  name: 'Kebab',          emoji: '🥙', tags: ['middle eastern', 'street food', 'meat'],  moods: ['cheap', 'quick meal'] },
  { id: 5,  name: 'Pasta',          emoji: '🍝', tags: ['italian'],                                moods: ['comfort food', 'cheap'] },
  { id: 6,  name: 'Ramen',          emoji: '🍜', tags: ['japanese', 'asian'],                      moods: ['comfort food', 'quick meal'] },
  { id: 7,  name: 'Tacos',          emoji: '🌮', tags: ['mexican', 'street food', 'spicy'],        moods: ['cheap', 'quick meal', 'comfort food'] },
  { id: 8,  name: 'Fried Chicken',  emoji: '🍗', tags: ['fast food', 'meat', 'american'],          moods: ['comfort food', 'cheap', 'quick meal'] },
  { id: 9,  name: 'Dumplings',      emoji: '🥟', tags: ['chinese', 'asian'],                       moods: ['comfort food', 'cheap'] },
  { id: 10, name: 'Steak',          emoji: '🥩', tags: ['american', 'grill', 'meat'],              moods: ['treat yourself'] },
  { id: 11, name: 'Burrito',        emoji: '🌯', tags: ['mexican'],                                moods: ['cheap', 'quick meal', 'comfort food'] },
  { id: 12, name: 'BBQ Ribs',       emoji: '🍖', tags: ['american', 'grill', 'meat'],              moods: ['treat yourself', 'comfort food'] },
  { id: 13, name: 'Hot Dog',        emoji: '🌭', tags: ['fast food', 'american', 'meat'],          moods: ['cheap', 'quick meal'] },
  { id: 14, name: 'Sandwich',       emoji: '🥪', tags: ['american', 'quick'],                      moods: ['cheap', 'quick meal', 'healthy-ish'] },
  { id: 15, name: 'Salad',          emoji: '🥗', tags: ['healthy', 'vegetarian'],                  moods: ['healthy-ish'] },
  { id: 16, name: 'Poke Bowl',      emoji: '🫙', tags: ['hawaiian', 'seafood', 'healthy'],         moods: ['healthy-ish', 'treat yourself'] },
  { id: 17, name: 'Wings',          emoji: '🍗', tags: ['fast food', 'meat', 'spicy'],             moods: ['comfort food', 'cheap'] },
  { id: 18, name: 'Crepes',         emoji: '🥞', tags: ['french', 'sweet'],                        moods: ['treat yourself', 'cheap'] },
  { id: 19, name: 'Indian Curry',   emoji: '🍛', tags: ['indian', 'spicy'],                        moods: ['comfort food', 'treat yourself'] },
  { id: 20, name: 'Pho',            emoji: '🍲', tags: ['vietnamese', 'asian'],                    moods: ['comfort food', 'healthy-ish'] },
  { id: 21, name: 'Pancakes',       emoji: '🥞', tags: ['american', 'sweet', 'breakfast'],         moods: ['comfort food', 'treat yourself'] },
  { id: 22, name: 'Nachos',         emoji: '🫔', tags: ['mexican', 'fast food', 'spicy'],          moods: ['cheap', 'comfort food'] },
  { id: 23, name: 'Gyros',          emoji: '🥙', tags: ['greek', 'street food', 'meat'],           moods: ['cheap', 'quick meal'] },
  { id: 24, name: 'Pad Thai',       emoji: '🍜', tags: ['thai', 'asian'],                          moods: ['cheap', 'comfort food'] },
  { id: 25, name: 'Fish & Chips',   emoji: '🐟', tags: ['british', 'seafood', 'fried'],            moods: ['comfort food', 'cheap'] },
  { id: 26, name: 'Shawarma',       emoji: '🌯', tags: ['middle eastern', 'street food', 'meat'],  moods: ['cheap', 'quick meal'] },
  { id: 27, name: 'Falafel',        emoji: '🧆', tags: ['middle eastern', 'vegetarian'],           moods: ['cheap', 'healthy-ish'] },
  { id: 28, name: 'Noodles',        emoji: '🍜', tags: ['asian', 'chinese'],                       moods: ['cheap', 'quick meal', 'comfort food'] },
  { id: 29, name: 'Waffles',        emoji: '🧇', tags: ['american', 'sweet', 'breakfast'],         moods: ['treat yourself', 'comfort food'] },
  { id: 30, name: 'Quesadilla',     emoji: '🫓', tags: ['mexican', 'quick'],                       moods: ['cheap', 'quick meal', 'comfort food'] },
  { id: 31, name: 'Dim Sum',        emoji: '🥟', tags: ['chinese', 'asian'],                       moods: ['treat yourself', 'comfort food'] },
  { id: 32, name: 'Grilled Salmon', emoji: '🐟', tags: ['seafood', 'healthy', 'grill'],            moods: ['healthy-ish', 'treat yourself'] },
]

export const MOODS = [
  { id: 'all',           label: 'All',           emoji: '✦' },
  { id: 'cheap',         label: 'Cheap Eats',    emoji: '💸' },
  { id: 'comfort food',  label: 'Comfort Food',  emoji: '🫂' },
  { id: 'healthy-ish',   label: 'Healthy-ish',   emoji: '🌿' },
  { id: 'treat yourself',label: 'Treat Yourself',emoji: '🍾' },
  { id: 'quick meal',    label: 'Quick Meal',    emoji: '⚡' },
]

export const EXCLUDES = [
  { tag: 'spicy',        label: 'Spicy 🌶️' },
  { tag: 'seafood',      label: 'Seafood 🦑' },
  { tag: 'fast food',    label: 'Fast Food 🍟' },
  { tag: 'meat',         label: 'Meat 🥩' },
  { tag: 'sweet',        label: 'Sweet 🍬' },
  { tag: 'japanese',     label: 'Japanese' },
  { tag: 'mexican',      label: 'Mexican' },
]
